# Generated by Django 4.0.4 on 2022-11-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackdata',
            name='typ',
            field=models.CharField(default='details', max_length=255),
        ),
    ]
